project:
  type: website

website:
  title: "Blog Acadêmico – Lucas C. Vasques"
  site-url: "https://vasqueslucas.github.io/blog-professor/"
  navbar:
    right:
      - text: "Início"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
      - text: "Posts"
        href: posts/

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
